# Generated by Django 4.0.4 on 2022-04-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_system', '0002_classes_group_remove_courses_institute_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Test_All',
        ),
    ]
