# Generated by Django 4.0.4 on 2022-04-26 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_system', '0003_rename_test_test_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='courses_names',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college_system.courses'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='group_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college_system.group'),
        ),
    ]
